from CipherFunctions import *

# reading = ReadFromFile("tmp.txt")
# print(len(reading.split()))
# permuted = TakeInitialPermutationString(key_text=reading,key_combination="0246813579")
# print(permuted)
# print("Len of permuted {}".format(len(permuted)))
# bin_dat = ConvertDataToBinaries(permuted)
# print(bin_dat)
# shift_bin = EightBitsRightShiftRotate(eight_data=bin_dat,shift_ratio=4)
# print("---------------")
# print(shift_bin)
# # print(len(bin_dat))
# CipherText(text_binary=bin_dat,key="ka")

leng = CipherTextNew(file_name="tmp.txt",key="rm")
sec2 = CipherTextNew(file_name="mailm.txt",key="rm")
inv_per = TakeInitialPermutationBinaryCipherArray(sec2,"0516273849")
print("Last stage inverse permutation started..")
print(inv_per)
inv_per = TakeInitialPermutationBinaryCipherArray(inv_per,"0246813579")
print("Final Inverse permutation Complete !!")

#print(len(leng))
#print(len(sec2))
#print(ReadFromFile("mailm.txt"))